force-app/main/default/objects/Bail__c/Bail__c.object-meta.xml
<CustomObject>
    <label>Bail</label>
    <nameField>
        <displayFormat>BAIL-{0000}</displayFormat>
        <label>Numéro de Bail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bail__c/fields/Locataire__c.field-meta.xml
<CustomField>
    <fullName>Locataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Locataire associé au bail</description>
    <label>Locataire</label>
    <referenceTo>Locataire__c</referenceTo>
    <relationshipLabel>Baux</relationshipLabel>
    <relationshipName>Baux</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bail__c/fields/Montant_Charges__c.field-meta.xml
<CustomField>
    <fullName>Montant_Charges__c</fullName>
    <description>Montant des charges mensuelles</description>
    <label>Montant des charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bail__c/fields/Montant_Loyer__c.field-meta.xml
<CustomField>
    <fullName>Montant_Loyer__c</fullName>
    <label>Montant Loyer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bail__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locataire__c/Locataire__c.object-meta.xml
<CustomObject>
    <label>Locataire</label>
    <nameField>
        <label>Nom complet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locataires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Locataire__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Paiement__c/Paiement__c.object-meta.xml
<CustomObject>
    <description>Objet pour gérer les paiements</description>
    <label>Paiement</label>
    <nameField>
        <displayFormat>PAIE-{0000}</displayFormat>
        <label>Numéro de paiement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paiements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Paiement__c/fields/Bail__c.field-meta.xml
<CustomField>
    <fullName>Bail__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bail associé au paiement</description>
    <label>Bail</label>
    <referenceTo>Bail__c</referenceTo>
    <relationshipLabel>Paiements</relationshipLabel>
    <relationshipName>Paiements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Date_Encaissement__c.field-meta.xml
<CustomField>
    <fullName>Date_Encaissement__c</fullName>
    <label>Date Encaissement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Date_Paiement__c.field-meta.xml
<CustomField>
    <fullName>Date_Paiement__c</fullName>
    <label>Date Paiement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Locataire__c.field-meta.xml
<CustomField>
    <fullName>Locataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Locataire associé au paiement</description>
    <label>Locataire</label>
    <referenceTo>Locataire__c</referenceTo>
    <relationshipLabel>Paiements</relationshipLabel>
    <relationshipName>Paiements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Montant_Charges__c.field-meta.xml
<CustomField>
    <fullName>Montant_Charges__c</fullName>
    <label>Montant Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Montant_Loyer__c.field-meta.xml
<CustomField>
    <fullName>Montant_Loyer__c</fullName>
    <label>Montant Loyer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Moyen_Paiement__c.field-meta.xml
<CustomField>
    <fullName>Moyen_Paiement__c</fullName>
    <label>Moyen de Paiement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Virement</fullName>
                <default>true</default>
                <label>Virement</label>
            </value>
            <value>
                <fullName>Chèque</fullName>
            </value>
            <value>
                <fullName>Espèces</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Periode_Debut__c.field-meta.xml
<CustomField>
    <fullName>Periode_Debut__c</fullName>
    <label>Période Début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Periode_Fin__c.field-meta.xml
<CustomField>
    <fullName>Periode_Fin__c</fullName>
    <label>Période Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Quittance_Generee__c.field-meta.xml
<CustomField>
    <fullName>Quittance_Generee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quittance Générée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Reference_Paiement__c.field-meta.xml
<CustomField>
    <fullName>Reference_Paiement__c</fullName>
    <label>Référence Paiement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Paiement__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
            </value>
            <value>
                <fullName>Rejeté</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClonePaiementUtility.cls
public with sharing class ClonePaiementUtility {

    /* ===== INPUT FLOW ===== */
    public class ClonepaiementsRequest {
        @InvocableVariable(required=true label='Id bail locatif')
        public Id bailLocatifId;

        @InvocableVariable(required=true label='Année à clôner')
        public String sourceYear;

        @InvocableVariable(required=true label='Nouvelle année')
        public String targetYear;
    }

    /* ===== OUTPUT FLOW ===== */
    public class ClonePaiementsResult {
        @InvocableVariable
        public Boolean success;

        @InvocableVariable
        public String message;
    }

    /* ===== INVOCABLE METHOD ===== */
    @InvocableMethod(
        label='Clôner les paiements'
        description='Clone les paiements d une année vers une autre'
    )
    public static List<ClonePaiementsResult> clonePaiements(
        List<ClonepaiementsRequest> requests
    ) {
        List<ClonePaiementsResult> results = new List<ClonePaiementsResult>();

        for (ClonepaiementsRequest req : requests) {
            ClonePaiementsResult result = new ClonePaiementsResult();

            try {
                Integer sourceYear = Integer.valueOf(req.sourceYear);
                Integer targetYear = Integer.valueOf(req.targetYear);

                /* 1️⃣ Récupération des dépenses */
                List<Paiement__c> paiementsSource = [
                    SELECT Id, Date_Encaissement__c, Date_Paiement__c, Statut__c, Bail__c, Locataire__c, 
                           Montant_Charges__c, Montant_Loyer__c, Moyen_Paiement__c,Notes__c, Periode_Debut__c, Periode_Fin__c, Quittance_Generee__c, Reference_Paiement__c
                    FROM Paiement__c
                    WHERE Bail__c = :req.bailLocatifId
                    AND CALENDAR_YEAR(Date_Paiement__c) = :sourceYear
                ];

                if (paiementsSource.isEmpty()) {
                    result.success = false;
                    result.message =
                        'Aucune paie trouvée pour l\'année ' + sourceYear + '.';
                    results.add(result);
                    continue;
                }

                /* 2️⃣ Duplication */
                List<Paiement__c> paiementsACreer = new List<Paiement__c>();

                for (Paiement__c paie : paiementsSource) {
                    Paiement__c clonePaie = paie.clone(false, true, false, false);

                    Date oldDate = paie.Date_Paiement__c;
                    Date newDate = Date.newInstance(
                        targetYear,
                        oldDate.month(),
                        oldDate.day()
                    );
                    
                    Date oldStartDate = paie.Periode_Debut__c;
                    Date newStartDate = Date.newInstance(
                        targetYear,
                        oldStartDate.month(),
                        oldStartDate.day()
                    );
                    
                    Date oldEndDate = paie.Periode_Fin__c;
                    Date newEndDate = Date.newInstance(
                        targetYear,
                        oldEndDate.month(),
                        oldEndDate.day()
                    );

                    clonePaie.Date_Paiement__c = newDate;
                    clonePaie.Date_Encaissement__c = newDate;
                    clonePaie.Periode_Debut__c = newStartDate;
                    clonePaie.Periode_Fin__c = newEndDate;
                    clonePaie.Statut__c = 'A payer';

                    paiementsACreer.add(clonePaie);
                }

                insert paiementsACreer;

                /* 3️⃣ Succès */
                result.success = true;
                result.message =
                    paiementsACreer.size() +
                    ' paiement(s) clonée(s) avec succès de ' +
                    sourceYear + ' vers ' + targetYear + '.';

            } catch (Exception e) {
                result.success = false;
                result.message =
                    'Erreur lors du clonage des paiements : ' +
                    e.getMessage();
            }

            results.add(result);
        }

        return results;
    }
}